(#74) Add bootstrap_script option for win_chocolatey
vexx32/choco-ansible pull request #77
Opened 2022-04-01 16:18 UTC by vexx32

## Description Of Changes

- Added `bootstrap_script` option for `win_chocolatey` module.
- Updated documentation for `source` option in `win_chocolatey`.
- Added some examples to the module doc for `win_chocolatey` around bootstrapping Chocolatey in a few different scenarios, including how to set the environment variables to target a specific nupkg to install if that's needed.
- Added a rudimentary test to ensure the functionality is actually working

## Motivation and Context

New option for `win_chocolatey` allows users to be completely explicit about the URL they want to pull a Chocolatey bootstrapping script from, rather than needing to rely on best-effort handling from the `source` option logic.

The additional documentation describes the actual behaviour of `source` in the bootstrapping scenario if the new option is provided, so users can better know what they should be using for a given scenario.

## Testing

- Added some tests to the win_chocolatey module to test out a bootstrap script
- Tested in the Vagrant environment ~~after some finagling and retrying with the finicky VM~~
- Tested in CI

## Change Types Made

* [ ] Bug fix (non-breaking change)
* [x] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)
* [x] Documentation updates

## Related Issue

Fixes #74 

## Change Checklist

* [ ] Requires a change to the documentation
* [x] Documentation has been updated
* [x] Tests to cover my changes, have been added
* [x] All new and existing tests passed

2022-04-01 16:19 UTC, vexx32 commented
/cc @watsonb, would love your thoughts on this if you have time to have a quick look and let me know if you like the direction I took with this and whether the additional documentation would have helped you sort out what you needed from the issue you filed?

2022-04-04 13:34 UTC, watsonb commented
Based on what I've read it seems like it would work for my situation.  Any idea of what version of the chocolatey collection this change will land in for me to test/evaluate?

2022-04-04 13:57 UTC, vexx32 commented
Probably around 1.3, but if you want to give it a test run at the moment, head over here https://dev.azure.com/ChocolateyCI/Chocolatey-Ansible/_build/results?buildId=269&view=artifacts&pathAsName=false&type=publishedArtifacts and download the `chocolatey.collection` artifact.

It will register with a 24.x version number that we use for testing so please only use it in a test environment, but should work normally. I believe `ansible-galaxy` will allow you to install the collection from a local file with `ansible-galaxy collection install <file path>`

2022-06-27 17:00 UTC, corbob requested changes
Just the one question about using what seems like an unneeded temporary variable 🤷

2022-06-27 17:59 UTC, vexx32 commented on chocolatey/tests/integration/targets/setup_win_chocolatey/files/bootstrap.ps1
> +[System.Net.ServicePointManager]::SecurityProtocol = $protocol
I think I did it this way because the default PSSA lints warn at 180 columns, which this would exceed, and Ansible would get mad about it 😅

2022-06-27 18:46 UTC, corbob submitted a review, later dismissed
Looks good to me. As with the previous one, I'll leave it for @Windos to test with Ansible unless you also want me to test with Ansible.

2022-06-28 14:51 UTC, Windos submitted a review, later dismissed
This looks good to me.

I've tested it on my Ansible 2.9 box (pointing it at the bootstrap script and nupkg that we use for C4B Azure) and it worked well.

Only thing to note is I did have to fully qualify the module name (`chocolatey.chocolatey.win_chocolatey`)... I think I had some weird caching issue going on as without that it was complaining about the `bootstrap_script` param not being supported.

Nice work!

2022-06-28 14:58 UTC, vexx32 commented
@Windos you were probably running into Ansible 2.9 having the chocolatey modules preinstalled as built-ins, so that makes sense. Thanks!

2022-06-28 19:10 UTC, corbob approved these changes
Looks good to me. I had some troubles testing it, but I'll open an issue to track those as they're unrelated to this PR.

2022-06-28 19:11 UTC, merged

2022-06-28 19:11 UTC, corbob commented
Thanks for getting those sorted @vexx32 👍