Add outdated packages to win_chocolatey_facts
vexx32/choco-ansible pull request #81
Opened 2022-06-06 12:58 UTC by voskampm

## Description Of Changes
Use 'choco outdated --limit-output' to create a list of packages for which an update is available and add that list to win_chocolatey_facts as: ansible_chocolatey.packages 

## Motivation and Context
Listing outdated packages is in my opinion a useful addition to win_chocolatey_facts.

## Testing
I have tested the new functionality in a playbook. It works when outdated packages are present and returns an empty list when no outdated packages are present. I also tried the instructions in https://github.com/voskampm/chocolatey-ansible/blob/outdated/testing-chocolatey/local-testing.md but got al kinds of errors creating the VM's. Example output:

```
       "outdated": [
            {
                "available_version": "21.7",
                "current_version": "21.6",
                "package": "7zip",
                "pinned": true
            },
            {
                "available_version": "21.7",
                "current_version": "21.6",
                "package": "7zip.install",
                "pinned": false
            },
            {
                "available_version": "8.0.28",
                "current_version": "8.0.27",
                "package": "mysql.odbc",
                "pinned": false
            }
        ],
```

## Change Types Made
* [ ] Bug fix (non-breaking change)
* [x] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)
* [ ] PowerShell code changes.

## Related Issue

Fixes: https://github.com/chocolatey/chocolatey-ansible/issues/80

## Change Checklist

* [x] Requires a change to the documentation
* [x] Documentation has been updated
* [x] Tests to cover my changes, have been added
* [x] All new and existing tests passed.
* [ ] PowerShell v2 compatibility checked.

2022-06-07 12:40 UTC, vexx32 commented
Thanks! This looks really good at first glance. I'll need to take some time as my work schedule permits to give it a proper review and think about tests we'll need to add before we can accept this, so it may take some time to get this merged.

That aside, thank you very much for the contribution! 💖

2022-06-12 10:25 UTC, voskampm commented
Hi: I finally got ansible-test working on my laptop. I will take a look at the necessary tests.

2022-06-19 10:33 UTC, voskampm commented
The win_chocolatey_facts target was my first choice for the 'Chocolatey outdated' tests but that target needed a lot of changes in order to be able to install and downgrade a test package. That's why I added the tests for this pull request to the win_chocolatey target because because that target already had the code to install and downgrade a test package.

2022-06-20 18:40 UTC, voskampm commented
I was not happy with the location of the tests for the outdated part of win_chocolatey_facts. I used the information in https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_integration_add.html#simplified-example to move the 'outdated' tests to target win_chocolatey_facts without duplicating the code needed to run the test.

2022-06-21 19:57 UTC, vexx32 requested changes
Wow, thank you! Really appreciate you taking the time to sort out the tests for us as well!

A few very small notes, but other than these this is fantastic, great job! 💖 🌸

2022-06-21 20:01 UTC, vexx32 commented
Can you also add the new `outdated` node to the [module's Python spec](https://github.com/chocolatey/chocolatey-ansible/blob/master/chocolatey/plugins/modules/win_chocolatey_facts.py) and add a similar style example into that doc here as well?

Once this and the other small changes have been addressed, we should be fine to merge this. Thanks so much for your work on this!

2022-06-22 12:30 UTC, vexx32 approved these changes
This looks great, thanks for sorting that out so quickly! 💖

2022-06-22 12:31 UTC, merged